name: Build and publish NPM packages

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (no actual publish)'
        type: boolean
        default: false

permissions:
  contents: read
  packages: read
  id-token: write

jobs:
  publish:
    name: Build & Publish NPM packages
    runs-on: ubuntu-latest
    environment: npmjs

    steps:
      - name: Get sources
        uses: actions/checkout@v6

      - name: Install pnpm
        uses: pnpm/action-setup@v6

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          cache-dependency-path: |
            pnpm-lock.yaml
            tools/make-sbom/pnpm-lock.yaml
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test devextreme-schematics
        run: pnpm --filter devextreme-schematics run test

      - name: Build devextreme-schematics
        run: pnpm --filter devextreme-schematics run build

      - name: Pack packages
        run: |
          package_cli_tgz="$(pnpm --filter devextreme-cli pack --json | jq -er 'if type=="array" then .[0].filename else .filename end')"
          package_schematics_tgz="$(pnpm --filter devextreme-schematics pack --json | jq -er 'if type=="array" then .[0].filename else .filename end')"

          echo "PACKAGE_CLI_TGZ=$(realpath "$package_cli_tgz")" >> "$GITHUB_ENV"
          echo "PACKAGE_SCHEMATICS_TGZ=$(realpath "$package_schematics_tgz")" >> "$GITHUB_ENV"

      - name: Upload packages
        uses: actions/upload-artifact@v7
        with:
          name: packages
          path: |
            ${{ env.PACKAGE_CLI_TGZ }}
            ${{ env.PACKAGE_SCHEMATICS_TGZ }}
          if-no-files-found: error
          retention-days: 14

      - name: Build SBOMs
        env:
          NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          pnpm set //npm.pkg.github.com/:_authToken="$NODE_AUTH_TOKEN"
          cd tools/make-sbom && pnpm install --frozen-lockfile && pnpm dx-make-sbom ../../ dist/ "devextreme-cli($PACKAGE_CLI_TGZ),devextreme-schematics($PACKAGE_SCHEMATICS_TGZ)"

      - name: Upload SBOMs
        uses: actions/upload-artifact@v7
        with:
          name: sbom
          path: tools/make-sbom/dist
          if-no-files-found: error
          retention-days: 14

      - name: Validate SBOMs
        uses: mpreyskurantov/github-actions/validate-sbom@sbom-val-dev
        with:
          input-format: json
          input-files: |
            tools/make-sbom/dist/devextreme-cli.cdx.json
            tools/make-sbom/dist/devextreme-schematics.cdx.json

      - name: Publish devextreme-cli
        run: pnpm publish "$PACKAGE_CLI_TGZ" --provenance ${{ inputs['dry-run'] && '--dry-run' || '' }}

      - name: Publish devextreme-schematics
        run: pnpm publish "$PACKAGE_SCHEMATICS_TGZ" --provenance ${{ inputs['dry-run'] && '--dry-run' || '' }}
