name: Build and publish NPM packages

on:
  workflow_dispatch:
    inputs:
      dry-run:
        description: 'Run in dry-run mode (no actual publish)'
        type: boolean
        default: false

permissions:
  contents: read
  id-token: write

jobs:
  publish:
    name: Build & Publish NPM packages
    runs-on: ubuntu-latest
    environment: npmjs

    steps:
      - name: Get sources
        uses: actions/checkout@v4

      - name: Install pnpm
        uses: pnpm/action-setup@v4

      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version-file: '.node-version'
          cache: 'pnpm'
          registry-url: 'https://registry.npmjs.org'

      - name: Install dependencies
        run: pnpm install --frozen-lockfile

      - name: Test devextreme-schematics
        run: pnpm --filter devextreme-schematics run test

      - name: Build devextreme-schematics
        run: pnpm --filter devextreme-schematics run build

      - name: Publish packages
        run: pnpm --filter './packages/*' publish --provenance ${{ inputs['dry-run'] && '--dry-run' || '' }}
